name: Build archlinux kernel (7.0 silvermont)

on:
  push:
    branches:
      - silvermont-7-latest  # O la rama que estés usando
  workflow_dispatch: # Esto te permite dispararlo a mano desde GitHub si querés

permissions:
  contents: write

env:
  _modprobeddb: "true"
  _modprobeddb_db_path: "${{ github.workspace }}/modprobed.db"
  _EXT_CONFIG_PATH: "${{ github.workspace }}/silvermont.cfg"
  PKGDEST: "/tmp/linux-tkg"
  tag_name: "kernel-7.0-silvermont"

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: 1 - Install git
        run: pacman -Syu --noconfirm git base-devel sudo

      - name: Checkout linux-tkg
        uses: actions/checkout@v4

      # 1. Install deps needed for building and sudo
      # 2. create a user "user" and give it passwordless sudo
      #    and necessary permissions
      #    because makepkg absolutely refuses to run as root
      - name: 2 - Prepare for makepkg
        run: |
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown user -R ..
          chown user -R /tmp

      - name: 3 - Compile Kernel
        run: su --preserve-environment user -c "yes '' | makepkg --noconfirm -s"
        
      - name: 4 - rename kernel config
        run: mv kernelconfig.new kernelconfig.arch.txt

      - uses: actions/upload-artifact@v4
        with:
          name: arch-kernel-packages
          path: |
            ${{ env.PKGDEST }}/linux*.pkg.tar.zst
            kernelconfig*.txt

      - name: "Create GitHub Release"
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ env.tag_name }}-${{ github.run_number }}"
          name: "Linux 7.0 · Silvermont · BORE · build #${{ github.run_number }}"
          body: |
            Kernel `7.0-tkg` · BORE · Clang/ThinLTO · modprobed-db (N2807)

            CPU  : Intel Celeron N2807 @ 1.58GHz (Bay Trail / Silvermont)
            Arch : x86_64 · 2 cores · 1 thread/core

            ```bash
            sudo pacman -U linux-*.pkg.tar
            ```

            - Branch: `${{ github.ref_name }}`
            - Commit: `${{ github.sha }}`
            - Run: [`#${{ github.run_number }}`](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          files: |
            ${{ env.work }}/linux-*.pkg.tar.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
