name: Build archlinux kernel (6.18-latest silvermont)

on:
  push:
    branches:
      - silvermont  # O la rama que estés usando
  workflow_dispatch: # Esto te permite dispararlo a mano desde GitHub si querés


env:
  _modprobeddb: "true"
  _modprobeddb_db_path: "${{ github.workspace }}/modprobed.db"
  _EXT_CONFIG_PATH: "${{ github.workspace }}/silvermont.cfg"
  PKGDEST: "/tmp/linux-tkg"

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:

      #- name: Copy my config to customization.cfg
      #  run: cp silvermont.cfg customization.cfg

      # We need to install git so the checkout is done with it
      #- name: Update mirrorlist
      #  run: |
      #    pacman -Sy --noconfirm reflector
      #    reflector --latest 50 --protocol http,https --sort rate --save /etc/pacman.d/mirrorlist

      - name: 1 - Install git
        run: pacman -Syu --noconfirm git

      - name: Checkout linux-tkg
        uses: actions/checkout@v4

      # 1. Install deps needed for building and sudo
      # 2. create a user "user" and give it passwordless sudo
      #    and necessary permissions
      #    because makepkg absolutely refuses to run as root
      - name: 2 - Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown user -R ..
          chown user -R /tmp

      # - name: "[debug] make dummy modprobed-db file for faster ci"
      #   run: |
      #     touch "${_modprobeddb_db_path}"
      #     echo "${_modprobeddb_db_path}"

      - name: 3 - Compile Kernel
        run: su --preserve-environment user -c "yes '' | makepkg --noconfirm -s"
        # run: |
        #   mkdir -p "$PKGDEST"
        #   echo "test" > "$PKGDEST"/linux-$_cpusched.pkg.tar.zst

      - name: 4 - rename kernel config
        run: mv kernelconfig.new kernelconfig.arch.txt

      - uses: actions/upload-artifact@v4
        with:
          name: arch-kernel-packages
          path: |
            ${{ env.PKGDEST }}/linux*.pkg.tar.zst
            kernelconfig*.txt
      
      - name: "5 - Create GitHub Release"
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "kernel-6.14-silvermont-${{ github.run_number }}"
          name: "Linux 6.18 - Intel Silvermont - build #${{ github.run_number }}"
          body: |
            Kernel 6.18-latest compilado para Intel Silvermont (Atom).
            - Branch: `${{ github.ref_name }}`
            - Commit: `${{ github.sha }}`
            - Config: `silvermont.cfg`
          files: |
            ${{ env.PKGDEST }}/linux*.pkg.tar.zst
            kernelconfig*.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
